sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t mrajput99/Udemy-Docker-CI-CD -f Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test